module.exports = {
  apps: [
    {
      name: 'rhie-coordinator',
      cwd: './apps/coordinator',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        CONFIG_PATH: '../../configs/platform.yaml',
      },
    },
    {
      name: 'rhie-client-registry-host',
      cwd: './apps/worker-host',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        CONFIG_PATH: '../../configs/platform.yaml',
        SERVICE_NAME: 'client-registry-host',
        WORKER_TYPES: 'client-registry',
        HEALTH_PORT: '9091',
      },
    },
    {
      name: 'rhie-encounter-id-host',
      cwd: './apps/worker-host',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        CONFIG_PATH: '../../configs/platform.yaml',
        SERVICE_NAME: 'encounter-id-host',
        WORKER_TYPES: 'encounter-id',
        HEALTH_PORT: '9092',
      },
    },
    {
      name: 'rhie-visit-encounter-host',
      cwd: './apps/worker-host',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        CONFIG_PATH: '../../configs/platform.yaml',
        SERVICE_NAME: 'visit-encounter-host',
        WORKER_TYPES: 'visit-encounter',
        HEALTH_PORT: '9093',
      },
    },
    {
      name: 'rhie-transfer-encounter-host',
      cwd: './apps/worker-host',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        CONFIG_PATH: '../../configs/platform.yaml',
        SERVICE_NAME: 'transfer-encounter-host',
        WORKER_TYPES: 'transfer-encounter',
        HEALTH_PORT: '9094',
      },
    },
    {
      name: 'rhie-observation-host',
      cwd: './apps/worker-host',
      script: 'dist/index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        CONFIG_PATH: '../../configs/platform.yaml',
        SERVICE_NAME: 'observation-host',
        WORKER_TYPES: 'observation',
        HEALTH_PORT: '9095',
      },
    },
  ],
};
